# Generated by Django 5.0.2 on 2024-03-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
