# Generated by Django 5.0.2 on 2024-03-05 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enduser', '0002_profile_followers_profile_follows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_logo', models.ImageField(blank=True, null=True, upload_to='space/logo')),
                ('space_banner', models.ImageField(blank=True, null=True, upload_to='space/banner')),
                ('admin', models.ManyToManyField(related_name='space_admin', to='enduser.organizer')),
                ('members', models.ManyToManyField(blank=True, related_name='space_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
